article/urls.py
from django.conf.urls import url
from . import views,list_views

urlpatterns=[
    # 文章栏目(自我分类)
    url(r'^article-column/$', views.article_column, name="article_column"),
    # 删除栏目
    url(r'^del-column/$',views.del_column,name="del_column"),
    # 编辑栏目
    url(r'^rename-column/$',views.rename_column,name="rename_column"),
    # 上传文章
    url(r'^article-post/$',views.article_post,name="article_post"),
    # 获取文章列表
    url(r'^article-list/$',views.article_list,name="article_list"),
    # 查看文章
    url(r'^article-detail/(?P<article_id>\d+)/(?P<slug>[-\w]+)/$',views.article_detail,name="article_detail"),
    # 删除文章
    url(r'^del-article/$',views.del_article,name="del_article"),
    # 编辑文章
    url(r'^edit-article/(?P<article_id>\d+)/$',views.edit_article,name="redit_article"),\
    # 查看list文章题目列表
    url(r'^list-article-titles/$',list_views.article_titles,name="article_titles"),
    # 查看list文章内容
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',list_views.read_article,name="list_article_detail"),
    # 获取作者全部文章
    url(r'^author-articles/(?P<username>[-\w]+)/$',list_views.article_titles,name="author_articles"),
    # 点赞文章
    url(r'^like-article/$',list_views.like_article,name="like_article"),
    # 文章tag设置
    url(r'^article-tags/$',views.article_tag,name="article_tags"),
    # 删除tag
    url(r'^del-tag/$',views.delete_tag,name="del_tag"),
]

blog/urls.py
from django.conf.urls import url
from .  import views

urlpatterns=[
    url(r'^$',views.blog_title,name="blog_title"),
    url(r'(?P<article_id>\d)/$',views.blog_article,name="bolg_detail"),
]

my_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    # url(r'^pwd_reset/',include("password_reset.urls",namespace='pwd_reset',app_name='pwd_reset')),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^home/',TemplateView.as_view(template_name="home.html"),name='home'),
    # 直接进入网站主页
    url(r'^$',TemplateView.as_view(template_name="home.html"),name='home'),
    url(r'^image/',include('image.urls',namespace='image',app_name='image')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
# 用于article获取url
from slugify import slugify

# 文章栏目对象
class ArticleColumn(models.Model):
    user=models.ForeignKey(User,related_name='article_column')
    column=models.CharField(max_length=200)
    created=models.DateField(auto_now=True)

    def __str__(self):
        return self.column

# 文章标签对象
class ArticleTag(models.Model):
    author=models.ForeignKey(User,related_name='tag')
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag

# 文章对象
class ArticlePost(models.Model):
    author=models.ForeignKey(User,related_name='article')
    title=models.CharField(max_length=200)
    slug=models.SlugField(max_length=500)
    column=models.ForeignKey(ArticleColumn,related_name="article_column")
    body=models.TextField()
    created=models.DateTimeField(default=timezone.now())
    updated=models.DateTimeField(auto_now=True)
    users_like=models.ManyToManyField(User,related_name="articles_like",blank=True)
    article_tag=models.ManyToManyField(ArticleTag,related_name='article_tag',blank=True)

    class Meta:
        ordering=("title",)
        index_together=(('id','slug'))

    def __str__(self):
        return self.title

    # 保存文章对象（slug额外保存）
    def save(self,*args,**kwargs):
        self.slug=slugify(self.title)
        super(ArticlePost,self).save(*args,**kwargs)

    # slug获取url
    def get_absolute_url(self):
        return reverse("article:article_detail",args=[self.id,self.slug])

    # slug获取url
    def get_url_path(self):
        return reverse("article:list_article_detail",args=[self.id,self.slug])

# 评论对象
class Comment(models.Model):
    article=models.ForeignKey(ArticlePost,related_name="comments")
    commentator=models.CharField(max_length=90)
    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('-created',)

    def __str__(self):
        return "comment by {0} on {1}".format(self.commentator,self.article)

article/forms.py
from django import forms
from .models import ArticleColumn,ArticlePost,Comment,ArticleTag

# 管理此应用全部model中的类对应的form

class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model=ArticleColumn
        fields=("column",)


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model=ArticlePost
        fields=("title","body")

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=("commentator","body",)

class ArticleTagForm(forms.ModelForm):
    class Meta:
        model=ArticleTag
        fields=('tag',)

article/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

from .forms import ArticleColumnForm,ArticlePostForm,ArticleTagForm
from .models import ArticleColumn,ArticlePost,ArticleTag
# 使用python标准json库
import json

# 文章栏目管理,可ajax,需登录
@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method=="GET":
        # 获取文章所有栏目
        columns=ArticleColumn.objects.filter(user=request.user)
        column_form=ArticleColumnForm()
        return render(request,"article/column/article_column.html",{"columns":columns,"column_form":column_form})
    elif request.method=="POST":
        # 提交文章栏目(新增)
        column_name=request.POST['column']
        columns=ArticleColumn.objects.filter(user_id=request.user.id,column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user,column=column_name)
            return HttpResponse('1')

# 编辑栏目名称,可ajax,需登录,且使用post方式
@login_required(login_url='/account/login/')
@csrf_exempt
@require_POST
def rename_column(request):
    column_name=request.POST['column_name']
    column_id=request.POST['column_id']
    try:
        line=ArticleColumn.objects.get(id=column_id)
        line.column=column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")

# 删除栏目,同上
@login_required(login_url='/account/login/')
@csrf_exempt
@require_POST
def del_column(request):
    column_id=request.POST['column_id']
    try:
        line=ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

# 发布文章,ajax提交,必须登录
@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method=="POST":
        # 发布文章
        article_post_form=ArticlePostForm(request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article=article_post_form.save(commit=False)
                new_article.author=request.user
                new_article.column=request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tags=request.POST['tags']
                if tags:
                    for atag in json.loads(tags):
                        tag=request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        # 进入发布文章页面
        article_post_form=ArticlePostForm()
        article_column=request.user.article_column.all()
        article_tags=request.user.tag.all()
        return render(request,"article/column/article_post.html",{"article_post_form":article_post_form,"article_column":article_column,"tags":article_tags})

@login_required(login_url='/account/login')
def article_list(request):
    """
    为控制article分页，主要部分在templates/paginator.html页面中
    :param request:
    :return:
    """
    articles_list=ArticlePost.objects.filter(author=request.user)
    # 创建分页对象，每页最大数量为2
    paginator=Paginator(articles_list,2)
    # 获取当前page的值
    page=request.GET.get('page')
    try:
        # page()得到指定页面（当前）内容，参数必须为大于等于一的整数
        current_page=paginator.page(page)
        # object_list为Page对象的属性，得到该页所有对象列表
        articles=current_page.object_list
    # 若不是整数
    except PageNotAnInteger:
        current_page=paginator.page(1)
        articles=current_page.object_list
    # 若参数为空或没有page参数
    except EmptyPage:
        current_page=paginator.page(paginator.num_pages)
        articles=current_page.object_list
    return render(request, 'article/column/article_list.html',{"articles":articles,"page":current_page})

# 查看文章
@login_required(login_url='/account/login')
def article_detail(request,article_id,slug):
    article=get_object_or_404(ArticlePost,id=article_id,slug=slug)
    return render(request,'article/column/article_detail.html',{"article":article})

# 删除文章
@login_required(login_url='/account/login')
@csrf_exempt
@require_POST
def del_article(request):
    article_id=request.POST["article_id"]
    try:
        article=ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

# 编辑文章
@login_required(login_url='/account/login')
@csrf_exempt
def edit_article(request,article_id):
    if request.method=="GET":
        article_columns=request.user.article_column.all()
        # article=ArticlePost.objects.get(id=article_id)
        article=get_object_or_404(ArticlePost,id=article_id)
        this_article_form=ArticlePostForm(initial={"title":article.title})
        this_article_column=article.column
        return render(request,'article/column/redit_article.html',{"article":article,"article_columns":article_columns,"this_article_form":this_article_form,"this_article_column":this_article_column})
    else:
        redit_article=ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column=request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title=request.POST['title']
            redit_article.body=request.POST['body']
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")

# 新建文章tag
@login_required(login_url='/account/login')
@csrf_exempt
def article_tag(request):
    if request.method=="GET":
        article_tags=ArticleTag.objects.filter(author=request.user)
        article_tag_form=ArticleTagForm()
        return render(request,"article/tag/tag_list.html",{"article_tags":article_tags,"article_tag_form":article_tag_form})
    if request.method=="POST":
        tag_post_form=ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag=tag_post_form.save(commit=False)
                new_tag.author=request.user
                new_tag.save()
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")

# 删除tag
@login_required(login_url='/account/login')
@csrf_exempt
@require_POST
def delete_tag(request):
    tag_id=request.POST['tag_id']
    try:
        tag=ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

templates/article/tag/tag_list.html
{% extends 'article/base.html' %}

{% load staticfiles %}

{% block title %}标签列表{% endblock %}

{% block content %}
    <div>
        <p>添加文章标签</p>
        <form class="form-horizontal" action="." method="post">{% csrf_token %}
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>文章标签</span></div>
                <div class="col-md-10 text-left">{{ article_tag_form.tag }}</div>
            </div>
            <div class="row">
                <input type="submit" class="btn btn-primary btn-lg" style="margin-left: 200px;margin-top: 10px;"
                       value="添加" id="add_tag">
            </div>
        </form>
    </div>
    <div>
        <p>已有标签列表</p>
        <table class="table table-hover">
            <tr>
                <td>序号</td>
                <td>文章标签</td>
                <td>操作</td>
            </tr>
            {% for article_tag in article_tags %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ article_tag.tag }}</td>
                    <td>
                        <a name="delete" href="javascript:" onclick="delete_tag(this,'{{ article_tag.id }}','{{ article_tag.tag }}')"> <i
                                class="glyphicon glyphicon-trash"></i>
                        </a>
                    </td>
                </tr>
                {% empty %}
                <p>你还未添加任何标签</p>
            {% endfor %}
        </table>
    </div>
{% endblock %}
{% block javascript %}
<script>
$(function () {
    $("#add_tag").click(function () {
        tag=$("#id_tag").val()
        $.ajax({
            url:"{% url 'article:article_tags' %}",
            type:"POST",
            data:{"tag":tag},
            success:function (e) {
                if(e=="1"){
                    layer.msg("新标签添加成功");
                    parent.location.reload();
                }
                else if(e=="2"){
                    layer.msg("新标签添加失败");
                }
                else if(e=="3"){
                    layer.msg("标签无效");
                }
            },
            error:function () {
                layer.msg("无法连接到服务器")
            }
        })
    })
});
function delete_tag(the,id,tag) {
    layer.open({
        type:1,
        skin:"layui-layer-rim",
        title:"删除文章标签",
        content:'<div class="text-center" style="margin-top:20px"><p>确定删除文章标签《'+tag+'》?</p></div>',
        btn:["确定","取消"],
        yes:function () {
            $.ajax({
                url:'{% url "article:del_tag" %}',
                type:"POST",
                data:{"tag_id":id},
                success:function (e) {
                    if(e=="1"){
                        layer.msg("删除完成");
                        parent.location.reload()
                    }else{
                        layer.msg("删除失败");
                    }
                },
                error:function () {
                    layer.msg("无法连接到服务器");
                }
            })
        }
    })
}
</script>
{% endblock %}