account/urls.py
from django.conf.urls import url
from . import views

# from django.conf import settings
# ???
from django.contrib.auth import views as auth_views

urlpatterns = [
    # 旧的用户登录方式
    # url(r'^login/$',views.user_login,name='user_login'),

    # 新的用户登录注册方式，使用了django自带的函数
    url(r'^login/$', auth_views.login, {"template_name": "account/login.html"}, name="user_login"),
    url(r'logout/$', auth_views.logout, {"template_name": "account/logout.html"}, name="user_logout"),
    url(r'^register/$', views.register, name="user_register"),

    # 用户个人信息及修改个人信息的功能，图片上传
    url(r'^my-informations/$', views.myself, name='my_information'),
    url(r'^edit-my-information/$', views.myself_edit, name="edit_my_information"),
    url(r'^my-image/$', views.my_image, name="my_image"),

    # 未完成的通过email修改密码的功能
    # url(r'^password-change/$', auth_views.password_change, {"post_change_redirect": "/account/password-change-done"},
    #     name='password_change'),
    # url(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),
    # url(r'^password-reset/$', auth_views.password_reset,
    #     {"template_name": "account/password_reset.html",
    #      "email_template_name": "account/password_reset_email.html",
    #      "subject_template_name": "/account/password_reset_subject.txt",
    #      "post_reset_redirect": "/account/password-reset-done"
    #      }, name='password_reset'),
    # url(r'^password-reset-done/$', auth_views.password_reset_done,
    #     {"template_name": "account/password_reset_done.html"},
    #     name='password_reset_done'),
    #
    # url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm,
    #     {"template_name": "account/password_reset_confirm.html"}, name="password_reset_confirm"),
    #
    # url(r'^password-reset-complete/$', auth_views.password_reset_complete, name="password_reset_complete"),

]

article/urls.py
from django.conf.urls import url
from . import views,list_views

urlpatterns=[
    # 文章栏目(自我分类)
    url(r'^article-column/$', views.article_column, name="article_column"),
    # 删除栏目
    url(r'^del-column/$',views.del_column,name="del_column"),
    # 编辑栏目
    url(r'^rename-column/$',views.rename_column,name="rename_column"),
    # 上传文章
    url(r'^article-post/$',views.article_post,name="article_post"),
    # 获取文章列表
    url(r'^article-list/$',views.article_list,name="article_list"),
    # 查看文章
    url(r'^article-detail/(?P<article_id>\d+)/(?P<slug>[-\w]+)/$',views.article_detail,name="article_detail"),
    # 删除文章
    url(r'^del-article/$',views.del_article,name="del_article"),
    # 编辑文章
    url(r'^edit-article/(?P<article_id>\d+)/$',views.edit_article,name="redit_article"),\
    # 查看list文章题目列表
    url(r'^list-article-titles/$',list_views.article_titles,name="article_titles"),
    # 查看list文章内容
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',list_views.read_article,name="list_article_detail"),
    # 获取作者全部文章
    url(r'^author-articles/(?P<username>[-\w]+)/$',list_views.article_titles,name="author_articles"),
    # 点赞文章
    url(r'^like-article/$',list_views.like_article,name="like_article"),
    # 文章tag设置
    url(r'^article-tags/$',views.article_tag,name="article_tags"),
    # 删除tag
    url(r'^del-tag/$',views.delete_tag,name="del_tag"),
]

blog/urls.py
from django.conf.urls import url
from .  import views

urlpatterns=[
    url(r'^$',views.blog_title,name="blog_title"),
    url(r'(?P<article_id>\d)/$',views.blog_article,name="bolg_detail"),
]

image/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^list-images/$',views.list_images,name="list_images"),
    url(r'^upload-image/$',views.upload_image,name="upload_image"),
    url(r'^del-image/$',views.del_image,name="del_image"),
    url(r'^fall-images/$',views.fall_images,name="fall_images"),
]

my_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    # url(r'^pwd_reset/',include("password_reset.urls",namespace='pwd_reset',app_name='pwd_reset')),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^home/',TemplateView.as_view(template_name="home.html"),name='home'),
    # 直接进入网站主页
    url(r'^$',TemplateView.as_view(template_name="home.html"),name='home'),
    url(r'^image/',include('image.urls',namespace='image',app_name='image')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    {% block cssfiles %}{% endblock %}
</head>
<body>
<header>
{% include "header.html" %}
</header>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<footer>
    {% include "footer.html" %}
</footer>
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% block javascript %}{% endblock %}
</body>
</html>

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.helloworld.hhh</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com"><img class="img-responsive" width="100px" src="{% static '/img/logo.png' %}"></a>
        </div>
        <div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'home' %}">网站首页</a></li>
                <li><a href="{% url 'blog:blog_title' %}">博客</a></li>
                <li><a href="{% url 'article:article_titles' %}">文章</a></li>
                <li><a href="{% url 'image:fall_images' %}">美图</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px;">
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown" style="margin-top:8px;">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown">
                            {{ user.username }}<span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:my_information' %}">个人信息</a> </li>
                            <li><a href="{% url 'account:edit_my_information' %}">修改个人信息</a> </li>
{#                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>#}
                            <li><a href="{% url 'article:article_column' %}">管理后台</a></li>
                            <li><a href="#">修改密码</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'account:user_logout' %}">登出</a></li>
                        </ul>
                    </div>
                </li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">登录</a></li>
                    <li><a href="{% url 'account:user_register' %}">注册</a></li>
{#                    <li><a href="{% url "social:begin" "qq" %}">QQ登录 <!-- 这个登录标识注意要满足QQ互联的要求 --></a></li>#}
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

templates/home.html
{% extends 'base.html' %}

{% block title %}博客首页{% endblock %}

{% block content %}
<div class="text-center">
    <h1>欢迎！</h1>
    <h3>人生苦短，我用python</h3>
    {% load staticfiles %}
    <img src="{% static 'img/avatar.png' %}">
</div>
{% endblock %}

templates/paginator.html
<div class="pagination">
    <span class="step-links">
{#    若存在前一页#}
        {% if page.has_previous %}
{#            调用内置前往后一页#}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
    <span class="current">
{#        当前页#}
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>